### PR TITLE
[WIP] Initial dotenv setup

### LINKED ISSUE #2: Move constants to dotenv file
The is a constant variable storing the database name. This can be moved to and loaded from a dotenv file.

https://github.com/sarcoma/Invoicing/blob/master/invoicing/constants/resource_path.py

### PR DESCRIPTION
**Pull request by dnegreira**
Few questions:
Do you want to move only the DB name to dotenv ? (that is what is on #2)
How do you want to provision the DB_FILE environment variable:
Do you want to provision a default .env?
Do you want to set the environment variable at the runtime?

Any other comments feel free to let me know.
Closes #2

### CODE REVIEW

**Comment by OrderAndCh4oS** [comment]
I'm thinking perhaps the `.tex` files might go in there too.

I'm trying to suss out how you can change the `.db` and `.tex` files after pip install. If we could allow look for a .env in the home directory under `.invoicing/.env` that might give an easy way to override them. There is probably a better way to handle it. 

Having a debug mode in there would be useful, I want to have one `.db` for testing and a live one for use after pip install.

I'm thinking that when I package it up I can set it up to copy a `.env` to  `~/.invoicing/.env` with the live parameters, if that doesn't exist it'd use the local one with the testing `.db` and `.example.tex` files.

Thanks so much for the PR, I'll take a look.

**Comment by dnegreira** [comment]
Another way to do it is to set an environment variable instead of having a `.env` file.
If you do `export DB_FILE=testing.db` it will use that DB file instead of the one inside of the .env, so you can add it to your .bashrc if you want to.
Having the possibility of having the `.env` file in the home directory is also a good idea, I think I can build up that logic for you, if you want to.

Let me know how you want to proceed, still have few days free to work on this :)

**Comment by OrderAndCh4oS** [comment]
It'd be fantastic if you could thank you for working on that, it's a great help.

I think it needs to work out of the box if someone clones/forks it or installs it with `pip`, if you know what I mean. Whatever you think would work best, will be fine.

I'm just dealing with another PR right now will merge this in a moment.

**Comment by dnegreira** [comment]
Please bear in mind that with the current state the code will not work as it lacks the provisioning of the `.env`  hence my questions :)

**Comment by OrderAndCh4oS** [comment]
Nice, thanks so much, all merged.

**Comment by OrderAndCh4oS** [comment]
I see what you mean. I've added ".env.example" for now. I'm not sure how best to handle that. I'd probably just default to the test database if no .env is found.

**Pull request merged**
